Running in dev mode.
[
  [
    [ 'TBD Graphic Designer', '85' ],
    [ 'TBD Sr Graphic Designer', '130' ],
    [ 'TBD Creative Director', '135' ],
    [ 'TBD Sr Creative Director', '175' ],
    [ 'TBD Exec Creative Director', '190' ],
    [ 'TBD Productions Coordinator', '55' ],
    [ 'TBD Associate Producer', '80' ],
    [ 'TBD Producer', '95' ],
    [ 'TBD Sr Producer', '120' ],
    [ 'TBD Executive Producer', '185' ],
    [ 'TBD Assoc Creative Dir/Strategist', '105' ],
    [ 'Kyle Kirkup', '130' ],
    [ 'Brooke Southerland', '130' ],
    [ 'Cindy Ay', '130' ],
    [ 'Hannah Snell', '85' ],
    [ 'Sabatani Shetu', '85' ],
    [ 'Cody Arabie', '80' ],
    [ 'Alex Kolbe', '135' ],
    [ 'Joel Rausch', '190' ],
    [ 'Traci/Patricia Landsdowne', '190' ],
    [ 'Anna Mander', '195' ],
    [ 'Pete Williams', '190' ],
    [ 'Andres Toro', '195' ],
    [ 'Clint Washington', '175' ],
    [ 'Jessica Weickert', '175' ],
    [ 'Ben Shlansky', '130' ],
    [ 'Jennifer Gardner', '190' ],
    [ 'Ben Birns', '115' ],
    [ 'David Guccione', '115' ],
    [ 'Megan Ferrara', '175' ],
    [ 'Jessica Musick', '175' ],
    [ 'Megan Moran', '175' ],
    [ 'Cary Ellston', '195' ],
    [ 'Matt Schrader', '195' ],
    [ 'Rachel Hermansader', '195' ],
    [ 'Emma Digiammarino', '90' ],
    [ 'Jade Arnone', '90' ],
    [ 'Lauren Hendrick', '90' ],
    [ 'Sandra Grady', '70' ],
    [ 'Sindhu Krishnan', '70' ],
    [ 'Alex Pfander', '95' ],
    [ 'Lauren Faber', '95' ],
    [ 'Craig Boyajan', '120' ],
    [ 'Ellen Karis', '120' ],
    [ 'Rachel Kava', '185' ],
    [ 'Wilder Smith', '120' ],
    [ 'Carol Fleming', '175' ],
    [ 'Katelyn Thompson', '80' ],
    [ 'Katie Muller', '80' ],
    [ 'Amy Williams', '185' ],
    [ 'Andrea Argiro', '185' ],
    [ 'Michael Newsome', '185' ],
    [ 'Sandra Tansky', '185' ],
    [ 'Scotland Reid', '185' ],
    [ 'Robin Gold', '195' ],
    [ 'Anna Mazotta', '55' ],
    [ 'Austen Denenny', '55' ],
    [ 'Chris Endler', '55' ],
    [ 'Georgia Gooding', '55' ],
    [ 'Kimberly Bertrand', '55' ],
    [ 'Ben Leininger', '185' ],
    [ 'Lucy Simmons', '185' ]
  ]
]
